### ISSUE TITLE
Problem s parsovanim datumov

### ISSUE THREAD

**Issue by tomaj** [BRACKETS-by-TRIAD/remp-segment-builder#10]
mam segment ktory vracia takyto detail:

```
{"status":"ok","segment":{"id":272,"version":2,"name":"testujem cas","code":"testujem-cas_254","table_name":"users","fields":["users.id","email","first_name","last_name"],"criteria":{"version":"1","nodes":[{"type":"operator","operator":"AND","nodes":[{"type":"criteria","key":"active_subscription","negation":false,"values":{"active_at":{"type":"absolute","absolute":{"gte":"2018-12-29T00:00:00.000Z","lt":"2018-12-30T00:00:00.000Z"}}}}]}]},"group_id":1}}
```

ked sa nacita tak to vyzera v segmenteri takto:
![image](https://user-images.githubusercontent.com/446736/50512253-6efb2800-0a91-11e9-8eed-3a60b01cc3a6.png)

a posiela to potom do api ako napriklad counts taketo data:
```
{"table_name":"users","criteria":{"version":"1","nodes":[{"type":"operator","operator":"AND","nodes":[{"type":"criteria","key":"active_subscription","negation":false,"values":{"active_at":{"type":"absolute","absolute":{"gte":null,"lt":null}}}}]}]}}
```

kde su tie gte a lt nastavene na null co neprechadza nasledne a konci to tym errorom hore

**Comment by tomaj** [comment]
toto je u nas aktualne celkom blocker problem :-( 
skuste pozriet prioritne ked budete moct riesit segmenter

**Comment by matejminar** [comment]
opravene https://github.com/BRACKETS-by-TRIAD/remp-segment-builder/commit/f57ccbda6a73eee4f59846570a1bae21c921ceca

nasiel som jeden problem/mozno nie problem s tymito datumami:
ak vyberiem operator Is a zvolim tyzdnovy picker - tak na server sa to posiela {gte: datum v pondelok, lt: datum v nedelu} - avsak ked nacitavam segment a idem to rozparsovat, tak segmentovac samozrejme da prvy operator gte a druhy operator lt - skratka neni tam uz Is s tyzdnovym pickerom... 
nevadi vam to?

toto zatvaram a ak treba, tak kludne otvorte na tento concern novy issue

**Comment by rootpd** [comment]
ja myslim ze nateraz je to OK. ak by sme mali pocit ze to vadi, tak tam mozeme dorobit nejake matchovanie, ale nemyslim si ze to bude nutne.

ked to je uz raz nastavene spravne, nemame dovod to tam upravovat (a otvarat picker) a ked to chceme nastavit na nieco ine, vybereme picker podla potreby.
