### ISSUE TITLE
Pri inicializacii Segmentera sa zavola count 3x

### ISSUE THREAD

**Issue by rootpd** [BRACKETS-by-TRIAD/remp-segment-builder#11]
Pripajam video: https://drive.google.com/file/d/1-2IutxGRx5uPo68wmLguGwgD7uUmTEW1/view

**Comment by matejminar** [comment]
ok, myslim, ze to mam, opravil som tu:
https://github.com/BRACKETS-by-TRIAD/remp-segment-builder/commit/2121fe06524701731e74aa50da485825a3ab0d0e

skuste a snad to uz bude ok, keby nieco, kludne reopenni
