### ISSUE TITLE
Po vybere kriteria s required parametrami sa spusti "nekompletny" count

### ISSUE THREAD

**Issue by rootpd** [BRACKETS-by-TRIAD/remp-segment-builder#12]
* Volanie `count` sa odpali v case, ked sa zobrazia povinne parametre, ale nemaju este vyplnene pocty/hodnoty.
* Volanie `count` sa odpali po kliknuti na "Add new criteria" (este pred vyberom konkretneho kriteria)

Pripajam video zahrnajuce oba pripady: https://drive.google.com/file/d/1-2IutxGRx5uPo68wmLguGwgD7uUmTEW1/view

**Comment by matejminar** [comment]
asi si nechtiac pastol video z #11 , posles prosim ta to spravne?
ten druhy bod viem, ale ten prvy by som chcel videt simulaciu

**Comment by matejminar** [comment]
ok, myslim, ze to mam, opravil som tu:
https://github.com/BRACKETS-by-TRIAD/remp-segment-builder/commit/2121fe06524701731e74aa50da485825a3ab0d0e

skuste a snad to uz bude ok, keby nieco, kludne reopenni
