### ISSUE TITLE
Casy su odosielane vzdy v UTC timezone

### ISSUE THREAD

**Issue by rootpd** [BRACKETS-by-TRIAD/remp-segment-builder#13]
Casove podmienky (napr. "Active subscription" - "Active at" - After) sa posielaju z Vuecka na server v UTC.

* Defaultne by sa mala brat timezona prehliadaca. Toto by sme brali len ako fallback.
* Primarny scenar by bol, ze timezonu urcime v konfiguracii pri inicializacii. Do tejto timezony by mali byt konvertovane serverove casy vracane cez API (to sa inak momentalne aj deje) a v tejto timezone by sa mali odoslat casy na server (namiesto UTC).

Timezonu mozeme zadavat v moment-friendly formate - https://momentjs.com/timezone/.

Odpozorovali sme to pri `counts` API aj pri ukladani.

**Comment by matejminar** [comment]
Ahoj, len ci tomu dobre rozumiem:

- timezone bude v config objekte (napr. window.Segments.config.TIME_ZONE)
- ak by nahodou nebola, tak fallback je timezone prehliadaca
- vsetky datumy vracane z api sa zobrazuju tak ako vy chcete, takze to neriesim
- vsetky datumy posielane na api nemaju byt vo formate: 2019-03-19T00:00:00.000Z ale napr. 2019-03-19T16:08:42+01:00

Moze byt?

**Comment by rootpd** [comment]
* timezone: ano, presne tak
* fallback: ano, presne tak
* vracane z api: ano, presne tak
* posielane do api: _nizsie_

Ten format je v podstate jedno ci je v Z alebo v +01:00, to si my rozparsujeme a skonvertujeme ako treba. Ide o to, ze sa deje toto:

* Vytvorim segment, kde vyklikam 12:00, na server teraz odide 12:00Z
* Refreshnem
* Zo serveru naspat pride 12:00Z
* Userovi sa zobrazi 13:00 (moj lokalny browserovy cas?)
* Bez nejakej interakcie ulozim
* Na server odide 13:00Z, co je realne 14:00+01 (uz sme dve hodiny mimo oproti povodnemu zameru)
* atd.

Cize nezalezi na konkretnej timezone v ktorej to ide na server, dokial to reprezentuje stale spravny cas. Dolezite je aby sa cas precitany v inpute nebral implicitne ako UTC ale aby sa bral v timezone, ktora bude nakonfigurovana.

**Comment by matejminar** [comment]
mam fixnute to co opisujes - skuste prosim testnut...
myslim, ze bez nastavovania timezone zo servera to fici v pohode - server vzdy pracuje s utc a frontend ukazuje v lokalnom case, ale neni som si isty tym posielanim timezone zo servera - mozno to ani nebude treba nakoniec, pokial to bez toho bude fungovat v poriadku

**Comment by rootpd** [comment]
diky moc, pomohlo.
