### ISSUE TITLE
Sandobx css

### ISSUE THREAD

**Issue by tomaj** [BRACKETS-by-TRIAD/remp-segment-builder#2]
ked includneme css zo sementera tak nam to rozbije zvysok crmka :-( - zmeni fonty a velkosti... 

vieme to nejak zasandboxovat ze sa to cele aplikuje len ne nejaky div? alebo kazda classa by mala nejaky prefix?

**Comment by matejminar** [comment]
ako sme teraz robili update vuetify na 1.3, tak v nom uz vacsinu class prefixli (btn -> v-btn)

mozte to prosim skusit teraz?

predpokladam, ze to moze aj tak este stale robit sarapatu, pretoze tu maju dost dlho nevyriesenu issue
https://github.com/vuetifyjs/vuetify/issues/1561#issuecomment-397815783
z ktorej vlastne vzniklo, ze poprefixuju classy, ale tusim grid napriklad este nemaju...

ak to stale nepojde, tak budeme musiet asi nieco vymysliet spolu, lebo nenapada mi nejaky pekny sposob, ako to cele scopnut (zopar skaredych by ich bolo)

**Comment by rootpd** [comment]
Stale nam to przni, akurat takym neprijemnym sposobom ze to je hned vidiet - velkost pisma v menu. Podla developer toolsov to ovplyvnuje toto pravidlo:

![peek 2018-12-06 08-48](https://user-images.githubusercontent.com/812909/49569433-39e93300-f934-11e8-9a5d-182c88b5abb2.gif)


```
html {
    font-size: 14px; // <-- toto tu
    overflow-x: hidden;
    text-rendering: optimizeLegibility;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    -webkit-tap-highlight-color: rgba(0,0,0,0);
}
```

Ake teda mame moznosti? Mne zatial napadol iframe ale moc sa mi do toho zatial nechce. Ak ale vsetko ostatne bude horsie, tak to radsej vyriesime tak.

**Comment by matejminar** [comment]
pokial vam nerobi problem napriklad ten grid, na ktory tam maju otvorenu uz strasne dlho tu issue,
ale iba nejaky jeden/par globalny html/body style, tak by mozno stalo za pouvazovanie, ze ci iba vo vasom pozadovanom css rule nezvysit specificitu - to by bolo asi najelegantnejsie riesenie... 

ak by to nahodou nebola schodna cesta, tak potom to este isti ten iframe, alebo potom skompilovane vuetify styly netahat priamo pekne z node_modules, ale spravit si vlastnu lokalnu upravenu kopiu (do coho by som velmi nerad, lebo stratime updaty a je to dost prasacina)

**Comment by rootpd** [comment]
V nasom CSS by ta specificita bola tiez asi prasacina, kedze by sme potrebovali hardcodnut hodnoty z bootstrapu. Nic ine mi vyslovene nevadi, ale zas bojim sa ze ked to nasadime do REMPu tak to tu sablonu rozbije uplne inym a zasadnejsim sposobom.

Ten upraveny styl, ktory by nebol z node_modules je tiez nieco, comu by sme sa radsej asi vyhli.

Ak teda nevidis inu cestu, tak to dame do iframu. @tomaj mozes to potom upravit u nas?

**Comment by tomaj** [comment]
Dal som to do iframe. Vyzera ze to ide dobre a vsetky tie side-efekty zmyzli. 👍
