### ISSUE TITLE
Preloading segmentera

### ISSUE THREAD

**Issue by tomaj** [BRACKETS-by-TRIAD/remp-segment-builder#3]
Aktualne mame pekne preloadery ktore sa tocia ked sa nacitavaju county pre jednotlive kriteria.

Ked to ale skusam s pomaly netom a requesty na samotny zoznam kriterii, resp. na nacitanie ktirerii segmentu ktory sa loaduje idu pomaly tak sa to cele zda take "zaseknute" - vieme dat aj nejaky globoalny preloader pred tu celu inicializaciu? resp. nejak skuste zauditovat vsetky requesty co to robi a nejak to vyskusajte zvizualizovat aby user vedel ze sa na nieco caka

**Comment by matejminar** [comment]
Taky ten globalny mame celkom napravo hore okna.
Aha tu:
https://remp-segment.brackets.sk/

Len je pravda, ze ak to bude len v nejakom divku a ten segment builder v nom na plnu sirku, tak by to mozno bolo lepsie dat niekde inde.
Spravil som taky ten horny celosirkovy natahovaci progress bar, ked sa natahujhu tie uvodne blueprinty a ostatne veci:
https://github.com/BRACKETS-by-TRIAD/remp-segment-builder/commit/fece19be7250d3d81e272694d28473c39185e39d
