### ISSUE TITLE
Okraje segmentera

### ISSUE THREAD

**Issue by tomaj** [BRACKETS-by-TRIAD/remp-segment-builder#4]
Aktualne ked vlozim segmenter do velkeho divu tak sa mi nacita stale len do stredu pricom z hora je vyrazne posunuty a aj na bokoch - cca taketo nieco https://www.dropbox.com/s/ftddels38vsprfn/Screenshot%202018-11-30%2010.37.35.png?dl=0

vieme to upravit tak aby ten sivy okraj bol povedzme 10px a celu velkost toho by sme nastavovali z vonku - cize by bol de-facto 100% width (okrem toho maleho okraja) - vieme to potom u nas uz nastavit podla potreby ako budeme chciet

**Comment by matejminar** [comment]
fixed https://github.com/BRACKETS-by-TRIAD/remp-segment-builder/commit/534409621b29e897f2d1dde36adb79a9480c51a8
