### ISSUE TITLE
Warningy v developer console

### ISSUE THREAD

**Issue by rootpd** [BRACKETS-by-TRIAD/remp-segment-builder#5]
Ahojte,

developer konzola hlasi dva warningy ohladne deprecated komponentu a jednej jej property. Poriesme to este pred finalnym nasadenim, nech nemame v novej veci deprecated referencie.

```
[Vuetify] '<v-select autocomplete>' is deprecated, use '<v-autocomplete>' instead

found in

---> <VSelect>
       <FieldsPicker> at FieldsPicker.vue
         <VCard>
           <ThemeProvider>
             <VDialog>
               <SaveButton> at SaveButton.vue
                 <VCard>
                   <VApp>
                     <App> at App.vue
                       <Root>
```

```
[Vuetify] 'max-height' is deprecated, use ':menu-props="{maxHeight:'auto'}"' instead

found in

---> <VAutocomplete>
       <FieldsPicker> at FieldsPicker.vue
         <VCard>
           <ThemeProvider>
             <VDialog>
               <SaveButton> at SaveButton.vue
                 <VCard>
                   <VApp>
                     <App> at App.vue
                       <Root>
```

**Comment by matejminar** [comment]
Pridal som README k projektu - instalovali ste ho cez yarn install ako je tam pisane?
Lebo ak ste dali npm install, tak moze byt, ze sa nerespektovala verzia vuetify a mate trosku vyssiu, v ktorej to uz hadze warningy, ze to bude deprecatnute?

V yarn.lock je 1.0.18 v ktorej to este nepise.
Teraz pozeram, ze vuetify je uz medicasom 1.3.11

Tak bud `rm -rf node_modules && yarn install && yarn serve`, alebo mozme este trosku casu investovat a dat vuetify na najaktualnejsiu verziu a pooopravovat v appke tych par veci, ktore budu pomenene... Co navrhujete?

**Comment by palypster** [comment]
Kedze to je dlhodoba vec, ja by som navrhoval este investovat, nech hned na zaciatku nezaciname s uz neaktualnou. Ale @rootpd nech rozhodne.

**Comment by rootpd** [comment]
@tomaj Pamatas si ci si daval `yarn` alebo `npm`? 

Osobne som za to dat to na tu vyssiu verziu este teraz. Ak by ste sa ale na niecom zasekli a vyzeralo by to na dlhsie tak to nechajme tak ako to je - nemusime to tam mat za kazdu cenu

**Comment by tomaj** [comment]
ja mam pocit ze som daval yarn, ale ruku do ohna by som za to nedal

**Comment by matejminar** [comment]
Bolo to tym 👍
Mame to updatenute a poupravovane vsetky zmenene vecicky.
https://github.com/BRACKETS-by-TRIAD/remp-segment-builder/commit/6aad37ca7d9db78721960155079902c78fbfea47
