### ISSUE TITLE
Zmena fieldov na selectovanie spusti prepocet poctu ludi v segmente

### ISSUE THREAD

**Issue by rootpd** [BRACKETS-by-TRIAD/remp-segment-builder#6]
Toto je zmena, ktora nijak velkost segmentu neovplyvnuje. V tomto pripade by sa teda prepocitat nemalo nic (chcem usetrit system od prepocitavania ked to nie je nutne, nie je to lacna operacia).

![peek 2018-12-06 08-46](https://user-images.githubusercontent.com/812909/49569153-6fd9e780-f933-11e8-8756-cdf8dd61be0b.gif)

**Comment by matejminar** [comment]
ok a suggested segments sa maju refetchnut?
neviem ci vam zalezia aj od fields, alebo nie.

**Comment by rootpd** [comment]
ak dobre pozeram, tak na fieldy sa nepozerame pri porovnavani; cize nerefetchujme ani odporucania

**Comment by matejminar** [comment]
upravene 👍 
spravil som aj refactor porovnavania payloadov na object deep comparison, bude to rychlejsie ako doteraz cez porovnavacku stringifynutych objectov
