### ISSUE TITLE
Viacnasobne ulozenie segmentu

### ISSUE THREAD

**Issue by tomaj** [BRACKETS-by-TRIAD/remp-segment-builder#8]
Aktualne ked vytvorim cez segmenter novy segment - "kliknem na Save" - tak sa vytvori segment, co je spravne. problem je ked kliknem znovu tak sa ulozi novy segment. Potrebujeme ohandlovat stav ked sa uz ulozi segment aby si komponenta ulozila idecko a nasledne ked upravujeme segment tak to posielala ako update segmentu.

**Comment by matejminar** [comment]
opravene https://github.com/BRACKETS-by-TRIAD/remp-segment-builder/commit/268c4bfaffd811938d41d34d4271a4c3fdf7f122

**Comment by tomaj** [comment]
Diki moc!
