### ISSUE TITLE
Cancel button otvarat do hlavneho okna

### ISSUE THREAD

**Issue by tomaj** [BRACKETS-by-TRIAD/remp-segment-builder#9]
Dalsi mse segmenter do iframu co sposobilu mensi problem s buttonom cancel ktory sa otvara aktualne v ramci iframu. treba do neho pridat `target="_top"` predpokladam

**Comment by matejminar** [comment]
pridane, skusal som si to nasimulovat a otvaralo to pekne, tak snad pojde aj u vas

**Comment by tomaj** [comment]
funguje aj u nas paradne 👍
